blog/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time : 2022/7/3 13:07
# @Author : firworkseasycold
# @Email : 1476094297@qq.com
# @File : urls.py
# @Software: PyCharm
from django.urls import path
from . import views

# app_name="blog" #参看主路由分发是否需要

urlpatterns=[
    path('note_index',views.note_index,name='note_index'), #显示所有博客，可以根据？指定
    path('detail/<int:id>',views.note_detail,name='note_detail'),
    path('add',views.add_note,name='add_note'),
    path('delete/<int:id>',views.delete_note,name='delete_note'),
    path('update/<int:id>',views.update_note,name='update_note'),
    # path('searchtag/<int:id>',views.searchtag,name='search_tag'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,re_path,include #include为新添加内容,进行路由分发
from . import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [


    path('admin/', admin.site.urls),
    path('',views.index,name='index'),  #首页
    #表示之匹配 index 开头，并且index结尾的路径，等同上一个，使用re_path写法
    # re_path(r'^index/$', views.index, name='index'),#只有re_path可使用正则
    path('tt',views.tt,name='tt'),
    path('hello/<int:age>/<name>/', views.hello, {'key': "val"}), #路由参数传递示例，将int,age,key直接给后端
    #这里使用路由分发
    # 如果使用命名空间有问题:原因在app下的url.py要加app_name='';或者必须将include第⼀个参数设置为元组类型
    # 路由分发作用当一个项目中包含多个app，每个app中都有命名相同的标识符时，例如index，能够使每次访问都能得到想要的结果（访问指定变量）
    # path('firstapp/',include('firstapp.urls',namespace='firstapp')),
    path('firstapp/',include(('firstapp.urls','firstapp'),namespace='firstapp')), #这里使用元组来应对命名空间,测试用
    path('camera/',include('camera.urls',namespace='camera')), #测试用

    path('users/',include('users.urls',namespace='users')),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    re_path('mdeditor/', include('mdeditor.urls')),
    path('comment/',include(('comment.urls','comment'),namespace='comment')),
    path('democelery/',include(('democelery.urls','democelery'),namespace='democelery')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #这是配置上传的文件路径

users/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time : 2022/4/17 17:43
# @Author : firworkseasycold
# @Email : 1476094297@qq.com
# @File : urls.py
# @Software: PyCharm
from django.urls import path

from . import views

app_name='users' #使用二级路由必须项

urlpatterns=[
    path('register/',views.Register.as_view(),name='reg'),#注册，增加用户 cbv开发模式
    path("login/", views.Login.as_view(),name='login'),  #登录，cbv开发模式
    path("usersinfo/",views.Usersinfo.as_view(),name='usersinfo'),  #用户个人信息查看和修改

    path('logout/',views.logout,name='islogout'), #登出
    path('delete/<int:id>',views.delete_user,name='delete_user') ,#注销用户
    path('pwd_reset',views.Reset_passwords.as_view(),name='pwd_reset'), #邮件重置密码
    path('contact',views.Contactgly.as_view(),name='contact'), #留言
    path('introduce',views.introduce,name='introduce'), #问题介绍


    # path('register/',views.register,name='reg'),#注册，增加用户
    # path('reg/',views.reg), #注册的第二个写法测试用
    # path('login/',views.login,name='login'), #登录 #fbv开发模式


    # path('usersinfo/',views.usersinfo,name='usersinfo'),
    # path('list/',views.list,name='userslist'), #所有用户列表
    # path('delete/',views.delete_user,name='delete_user'), #删除用户
    path('test_form/',views.test_form), #测试form组件
]

templates/homepage/index.html
{% extends 'base.html' %}

{% block title %}
主页
{% endblock %}

{% block content %}
<div class="bg-light py-5">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder text-dark mb-2">树莓博客网</h1>
                    <p class="lead fw-normal text-dark-50 mb-4">一个多人博客站点</p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                        <a class="btn btn-outline-dark btn-lg px-4 me-sm-3" href="{% url 'blog:add_note' %}">创作</a>
                        <a class="btn btn-outline-dark btn-lg px-4" href="{% url 'users:reg' %}">注册</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5" src="{% static '/img/index_1.gif' %}" alt="..." /></div>
        </div>
    </div>
</div>


<!-- Blog preview section-->
<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">每日推荐</h2>
                    <p class="lead fw-normal text-muted mb-5">杂志上说，当你开始使用博客时，会发现，这世上总有几个人会专程去看你写的东西。</p>
                </div>
            </div>
        </div>
<!--        博客列表-->
        <div class="row gx-5">
            {% if articles %}
                {% for article in articles %}
                <div class="col-lg-4 mb-5">
                    <div class="card h-100 shadow border-0">
<!--                        <img class="card-img-top" src="https://dummyimage.com/600x350/ced4da/6c757d" width="600" height="350" alt="note_img" />-->
                        <img class="card-img-top" src="/media/{{article.note_img}}" width="600" height="200" alt="note_img" />
                        <div class="card-body p-4">
<!--                            标签-->

                            {% if article.tags.all %}
                            {% for tag in article.tags.all %}
<!--                            由于一些布局问题这里href点击跳转标签失效-->
                                <a class="badge bg-secondary text-decoration-none link-light" href="{% url 'blog:note_index' %}?tag={{ tag }}">
                                    {{ tag }}
                                </a>
                            {% endfor %}
                            {% else %}
                                <a class="badge bg-secondary text-decoration-none link-light" href="#!">无标签</a>
                            {% endif %}
<!--                            标题-->
                            <a class="text-decoration-none link-dark stretched-link" href="{% url 'blog:note_detail' article.id %}"><h5 class="card-title mb-3">{{ article.title }}</h5></a>
<!--                            正文-->
                            <p class="card-text mb-0">{{ article.content|slice:'100' }}</p>
                        </div>
                        <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                            <div class="d-flex align-items-end justify-content-between">
                                <div class="d-flex align-items-center">
<!--                                    <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" width="40" height="40" alt="tx" />-->
                                    <img class="rounded-circle me-3" src="/media/{{ article.user.tx }}" width="40" height="40" alt="tx" />
                                    <div class="small">
                                        <div class="fw-bold">{{ article.user.username }}</div>
                                        <div class="text-muted">{{ article.update_time }}; {{ article.click_num }}阅读</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'blog:note_detail' article.id %}" class="btn btn-primary">阅读文章</a>
                        </div>
                    </div>
                </div>
                {% empty %}
                <h4><span style="color: red">文章加载失败</span></h4>
                {% endfor %}
            {% else %}
            <h4><span style="color: red">没有文章</span></h4>
            {% endif %}
        </div>

        <!-- Call to action-->
    </div>
</section>
{% endblock %}