blog/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time : 2022/7/3 13:07
# @Author : firworkseasycold
# @Email : 1476094297@qq.com
# @File : urls.py
# @Software: PyCharm
from django.urls import path
from . import views

# app_name="blog" #参看主路由分发是否需要

urlpatterns=[
    path('note_index',views.note_index,name='note_index'), #显示所有博客，可以根据？指定
    path('detail/<int:id>',views.note_detail,name='note_detail'),
    path('add',views.add_note,name='add_note'),
    path('delete/<int:id>',views.delete_note,name='delete_note'),
    path('update/<int:id>',views.update_note,name='update_note'),
    # path('searchtag/<int:id>',views.searchtag,name='search_tag'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,re_path,include #include为新添加内容,进行路由分发
from . import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [


    path('admin/', admin.site.urls),
    path('',views.index,name='index'),  #首页
    #表示之匹配 index 开头，并且index结尾的路径，等同上一个，使用re_path写法
    # re_path(r'^index/$', views.index, name='index'),#只有re_path可使用正则
    path('tt',views.tt,name='tt'),
    path('hello/<int:age>/<name>/', views.hello, {'key': "val"}), #路由参数传递示例，将int,age,key直接给后端
    #这里使用路由分发
    # 如果使用命名空间有问题:原因在app下的url.py要加app_name='';或者必须将include第⼀个参数设置为元组类型
    # 路由分发作用当一个项目中包含多个app，每个app中都有命名相同的标识符时，例如index，能够使每次访问都能得到想要的结果（访问指定变量）
    # path('firstapp/',include('firstapp.urls',namespace='firstapp')),
    path('firstapp/',include(('firstapp.urls','firstapp'),namespace='firstapp')), #这里使用元组来应对命名空间,测试用
    path('camera/',include('camera.urls',namespace='camera')), #测试用

    path('users/',include('users.urls',namespace='users')),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    re_path('mdeditor/', include('mdeditor.urls')),
    path('comment/',include(('comment.urls','comment'),namespace='comment')),
    path('democelery/',include(('democelery.urls','democelery'),namespace='democelery')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #这是配置上传的文件路径

users/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time : 2022/4/17 17:43
# @Author : firworkseasycold
# @Email : 1476094297@qq.com
# @File : urls.py
# @Software: PyCharm
from django.urls import path

from . import views

app_name='users' #使用二级路由必须项

urlpatterns=[
    path('register/',views.Register.as_view(),name='reg'),#注册，增加用户 cbv开发模式
    path("login/", views.Login.as_view(),name='login'),  #登录，cbv开发模式
    path("usersinfo/",views.Usersinfo.as_view(),name='usersinfo'),  #用户个人信息查看和修改

    path('logout/',views.logout,name='islogout'), #登出
    path('delete/<int:id>',views.delete_user,name='delete_user') ,#注销用户
    path('pwd_reset',views.Reset_passwords.as_view(),name='pwd_reset'), #邮件重置密码
    path('contact',views.Contactgly.as_view(),name='contact'), #留言
    path('introduce',views.introduce,name='introduce'), #问题介绍


    # path('register/',views.register,name='reg'),#注册，增加用户
    # path('reg/',views.reg), #注册的第二个写法测试用
    # path('login/',views.login,name='login'), #登录 #fbv开发模式


    # path('usersinfo/',views.usersinfo,name='usersinfo'),
    # path('list/',views.list,name='userslist'), #所有用户列表
    # path('delete/',views.delete_user,name='delete_user'), #删除用户
    path('test_form/',views.test_form), #测试form组件
]

blog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone
from mdeditor.fields import MDTextField
from taggit.managers import TaggableManager
#
# class Tag(models.Model):
#     name=models.CharField(max_length=50,verbose_name='标签名',unique=True)
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         db_table='tag'
#         verbose_name = '标签表'
#         verbose_name_plural = verbose_name



class Note(models.Model): #(默认的数据库表名appname_classname,blog_note)
    """博客表"""
    objects = models.Manager()
    title = models.CharField('标题', max_length=100)
    desc=models.CharField('简介',max_length=256,default='暂无简介')
    # content = models.TextField('内容')
    content = MDTextField(verbose_name='正文')  # TextField修改为MDTextField
    note_img = models.ImageField(upload_to='uploads/blog/%Y/%m/%d', verbose_name='文章配图', default='uploads/blog/blog.jpeg')
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    update_time = models.DateTimeField('更新时间', auto_now=True)
    click_num=models.IntegerField(default=0,verbose_name='点击量')
    love_num=models.IntegerField(default=0,verbose_name='点赞量')
    # tag = models.ManyToManyField(to=Tag,verbose_name='标签',blank=True)  #blank用于表单的认证,默认False,true填写表单时允许为空
    # 文章标签
    tags = TaggableManager(blank=True)
    #多对多关系自动生成的关系表 note_tag,也可以指定through='',mysql里note表没有这个字段tag,从note需要note.tag.all()来拿
    user = models.ForeignKey('users.Usersdata', on_delete=models.CASCADE) #一对多

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def __str__(self):
        return self.title  # print时候会显示为这个内容

    # 新增一个get_absolute_url函数，重定向到详情页
    def get_absolute_url(self):
        return reverse('blog:note_detail', args=[self.id])  #这里id黄色不用管


    class Meta:
        db_table='note'
        verbose_name = '文章表'
        verbose_name_plural = verbose_name

blog/forms.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time : 2022/7/17 10:51
# @Author : firworkseasycold
# @Email : 1476094297@qq.com
# @File : forms.py
# @Software: PyCharm
from django import forms
from django.db import models

from .models import Note

# 自定义写文章的表单类
class NoteForm(forms.ModelForm):
    #这里写自定义字段
    class Meta:
        # 指明数据模型来源
        model = Note
        #定义表单包含的字段
        fields = ('title','note_img','tags','content')
        #如果所有
        # fields="__all__"
        #排除字段
        # exclude=["desc"]

    # def xxx(self):
    #     raise ('用 raise 手动引发的异常')

blog/views.py
import json
import re

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
import markdown
from django.views.generic import CreateView, DetailView


from tools.my_tool import * #这里红色不是错误（标记源根即可解决），tools为项目下与各app包同级别的自建包

from users.models import Usersdata
from comment.models import Comment
from .models import Note
from .forms import NoteForm
# Create your views here.

#博客主页不需要登录
def note_index(request):
    """使用分页后为/note_index>page=n
    展示所有用户所有所有博客（显示摘要）-和分页方法结合
    优化整合,添加不同排序组,click_num和update_time,根据get的查询条件,返回不同排序的对象数组,默认最新
    进一步增加搜索文章逻辑
    """
    if cache.get('all_article_list'):
        article_list=cache.get('all_article_list')
    else:
        article_list = Note.objects.all()
        cache.set('all_article_list',article_list,20)
    search=request.GET.get('search')
    order = request.GET.get('order')
    tag = request.GET.get('tag')
    user = request.GET.get('user') #这里前端给的是用户id，比较快

    # print(request.GET)
    if user and user != 'None':  #ValueError: Field 'id' expected a number but got 'None'.
        # print('使用用户')
        if cache.get(user):
            article_list = cache.get(user)
        else:
            article_list=article_list.filter(user=user)
            cache.set(user,article_list,20)
    if search:
        # print('使用了搜索')
        # 使用 Q对象进行联合搜素;icontains是不区分大小写的包含，中间用两个下划线隔开
        #给查询设置缓存
        if cache.get(search):
            article_list=cache.get(search)
        else:
            article_list = article_list.filter(Q(title__icontains=search) | Q(content__icontains=search))
            cache.set(search, article_list, 20)
    else:
        # 将search参数重置为空
        search='' #如果用户没有搜索操作，则search = request.GET.get('search')会使得search = None，而这个值传递到模板中会错误地转换成"None"字符串！等同于用户在搜索“None”关键字，这明显是错误的
    if order=='click_num':
        # print('点击排序')
        article_list = article_list.order_by("-click_num")
    else:
        # print('时间排序')
        article_list=article_list.order_by("-update_time") #获取所有查询到的数据 ,最好带排序,否则可能如下报错
    if tag and tag != 'None':
        # print('使用了标签')
        if cache.get(tag):
            article_list=cache.get(tag)
        else:
            article_list = article_list.filter(tags__name__in=[tag])
            cache.set(tag,article_list,20)
    # print(articles_list)
    #UnorderedObjectListWarning: Paginationmay yield inconsistent resultswith an unordered object_list:<class 'blog.models.Note'> QuerySet.
    # 分页 每页9条
    paginator = Paginator(article_list, 9) #这里才发数据
    # print('当前对象的总个数是:', paginator.count)
    # print('当前对象的面码范围是:', paginator.page_range)
    # print('总页数是：', paginator.num_pages)
    # print('每页最大个数:', paginator.per_page)
    # 获取url的页码
    cur_page = request.GET.get('page', 1)  #得到擦查询字符串page,没有则1
    # 得到默认的当前页
    articles = paginator.page(cur_page) #负责具体一页内容

    #把新变量order也传递到模板中？因为文章需要翻页,order给模板一个标识，提醒模板下一页应该如何排序;增加查询关键字search和内容
    content={'articles':articles,'order':order,'search':search,'user':user,}
    return render(request,'blog/note_index.html',content)



#博客详情不需要登陆验证
def note_detail(request, id):
    """对应id的博客详情
    """
    # 取出相应的文章
    article = get_object_or_404(Note, id=id)
    # print(article.user.username)
    # print(article.user.profile)
    # print(article.tag)#多对多这样子拿不到数据
    # print(article.tag.all()) #这样才可以,后面还可以接values（）
    # print(tags)
    # for tag in tags:
    #     print('tag:',tag)
    # 多对多查询参考：https: // blog.csdn.net / qq_40199698 / article / details / 97827706

    # # 配置markdown，将Markdown语法书写的文章渲染为HTML文本
    # # 将markdown语法渲染成html样式，第一个参数是需要渲染的文章正文article.content；第二个参数载入了常用的语法扩展，
    # article.content = markdown.markdown(article.content,
    #                                     extensions=[
    #                                         # 包含 缩写、表格等常用扩展
    #                                         'markdown.extensions.extra',
    #                                         # 语法高亮扩展
    #                                         'markdown.extensions.codehilite',
    #                                         #加入了 toc 拓展后，就可以在文中插入目录了。方法是在书写Markdown文本时，在你想生成目录的地方插入[TOC]标记即可
    #                                         'markdown.extensions.toc',
    #                                     ])
    # #发现有一大堆<\p>
    # #注意：Django出于安全的考虑，会将输出的HTML代码进行转义，这使得article.content中渲染的HTML文本无法正常显示。
    # #解决：前端html在article.content后加上 | safe过滤器
    # # 管道符|是Django中过滤器的写法，而|safe就类似给article.body贴了一个标签，表示这一段字符不需要进行转义了。


    #浏览量:
    # 如果非作者本人点击,点击量+1
    # 过滤作者;
    if request.session.get('userinfo', False):
        userinfo = request.session.get('userinfo', False)
        username = userinfo.get('username', False)  # 拿出session里存的主键;
        #上面两句这么写会报'bool' object has no attribute 'get',需要一个错误处理,因为我这里没要求必须登录,所以try
        if username != article.user.username:
            #浏览量+1 指定了数据库只更新click_num字段，优化执行效率
            article.click_num+=1
            article.save(update_fields=['click_num'])


    #后续建立评论app功能后
    #取出文章评论
    comment_list = Comment.objects.filter(article_id=id)  #从数据库找出该文章的评论数据对象
    # print(comment_list.count)
    # print(comment_list)

    # 需要传递给模板的对象：文章后续添加评论,标签
    context = {'article': article,'comment_list':comment_list}

    # 载入模板，并返回context对象
    return render(request, 'blog/note_detail.html', context)
# 或者使用如下
# class ArticleDetailView(DetailView):
#     model = Note
#     template_name = 'note_detail.html

@check_login
def add_note(request):
    """
    添加博客
    :param request:
    :return:
    """
    if request.method=="GET":
        # 创建表单类实例
        note_post_form = NoteForm()
        # 赋值上下文
        context = {'note_post_form': note_post_form}  #这个不能少
        return render(request,'blog/add_note.html',context)

    elif request.method=='POST':
        # 将提交的数据赋值到表单实例中
        note_post_form = NoteForm(data=request.POST) #如果model表单有upload文件,需要带上files=request.FILES,没有会报错
        # 判断提交的数据是否满足模型的要求
        if  note_post_form.is_valid(): #如果表单有数据，且无错误，则返回True,否则 False.
            # 保存数据，但暂时不提交到数据库中
            new_note = note_post_form.save(commit=False)
            #确定是否作者本人操作
            userinfo=request.session.get('userinfo',False) #去看我存的格式
            uid=userinfo.get('uid',False) #拿出session里存的主键
            new_note.user=Usersdata.objects.get(id=uid)
            # 将新文章保存到数据库中
            new_note.save()
            # 新增代码，保存 tags 的多对多关系提交的表单使用了commit=False选项，则必须调用save_m2m()才能正确的保存标签，就像普通的多对多关系一样。
            note_post_form.save_m2m()
            #返回到文章详情页/或者在类里使用def get_absolute_url(self):return reverse('some_url', args=(self.id,))
            return redirect("blog:note_detail",id=new_note.id)
            # return redirect("blog:note_index")
        # 如果数据不合法，返回错误信息
        else:
            messages.error(request,'表单有误,请重新填写')
            return render(request,'blog/add_note.html')

# 也可以直接使用视图函数发布博客,并配置路由
class AddArticleView(CreateView):
    model = Note
    template_name = 'add_note.html'
    # 通过CreateView，可以获取到正在创建的对象
    # fields表单显示字段，后面在模板中可以直接使用
    fields = '__all__'

@check_login
def update_note(request,id):
    '''
    	更新文章的视图函数
    	通过POST方法提交表单，更新
    	GET方法进入初始表单页面
    	id： 文章的id
    	'''
    # 获取需要修改的具体文章对象
    #文章的id会从detail页面里那里拿到
    article = Note.objects.get(id=id)

    # 过滤非作者的用户
    userinfo = request.session.get('userinfo', False)
    username = userinfo.get('username', False)  # 拿出session里存的主键
    # print(username)
    # print(article.user.username)
    if username != article.user.username:
        return HttpResponse("抱歉，你无权修改这篇文章。")

    # 判断用户是否为POST提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        note_post_form = NoteForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if note_post_form.is_valid():
            # 将表单获取的新title、content写入article数据
            article.title = request.POST['title']
            article.content = request.POST['content']
            # article.tags = request.POST['tags'] #这样写无效
            #关键是多对多的标签要注意
            tags_post=request.POST['tags'] #拿到的是带,的字符串
            # print(type(tags_post))
            tags_list_post=tags_post.split(',')  #分割为list
            tags_list=[]
            for i in tags_list_post:
                try:
                    i=eval(i)  #去除每个tag的""  #这里是处理tag初始化表单时自动加上“”的bug
                except:
                    pass
                tags_list.append(i)
            # print(tags_list)
            try:
                # https://blog.csdn.net/alexander068/article/details/119724017
                #Django多对多数据增删改查 http: // t.zoukankan.com / 17vv - p - 11723372.html
                article.tags.set(tags_list) #注意参数是个标签组成的列表
                article.save()
               #返回我的所有博客地址
                return redirect("blog:note_detail",id=id)
                # return HttpResponse('更新成功')
            except Exception as e:
                # 如果保存失败，返回错误信息
                messages.error(request,'修改失败，请重新填写！')
                return redirect("blog:update_note",id=id)
        # 如果数据不合法，返回错误信息
        else:
            messages.error(request, '表单内容有误，请重新填写！')
            return redirect("blog:update_note",id=id)

    # 如果用户GET请求获取数据
    else:
        # 创建表单类实例,直接将article文章对象也传递进去，作为默认值,分为初始化与未初始化
        note_post_form = NoteForm()
        note_post_form.fields['title'].initial=article.title
        note_post_form.fields['content'].initial=article.content
        note_post_form.fields['tags'].initial=article.tags.all() #发现一个bug,这里每次初始化会自动多出来"",所以上面post创建时候需要eval()过滤掉字符串的“”
        # note_post_form=NoteForm(initial = {'Email':article.title})
        # 参考https://www.cnblogs.com/yehua-night/p/14645942.html
        # print(note_post_form)
        # note_post_form["content"].initial=article
        context = {'note_post_form':note_post_form}
        # 将响应返回到模板中

templates/blog/add_note.html
{% extends 'base.html' %}

{% block title %}
新建博客
{% endblock %}
{% block content %}
<main class="bg">
<div class="container">
    <div class="row">
        <div class="col-12">
            <!-- 提交文章的表单 -->
            <form method="post" action="{% url 'blog:add_note' %}">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
<!--                &lt;!&ndash; 文章标题 &ndash;&gt;-->
<!--                <div class="form-group">-->
<!--                    &lt;!&ndash; 标签 &ndash;&gt;-->
<!--                    <label for="title">文章标题</label>-->
<!--                <label for="tags">标签</label>-->
<!--        <input type="text" -->
<!--               class="form-control col-3" -->
<!--               id="tags" -->
<!--               name="tags"-->
<!--                    &lt;!&ndash; 文本框 &ndash;&gt;-->
<!--                    <input type="text" class="form-control" id="title" name="title">-->
<!--&lt;!&ndash;                <div class="form-group">&ndash;&gt;-->
<!--&lt;!&ndash;                    <label for="tag">文章标签</label>&ndash;&gt;-->
<!--&lt;!&ndash;                    <input type="text" class="form-control"  id="tag" name="tag">&ndash;&gt;-->
<!--&lt;!&ndash;                </div>&ndash;&gt;-->
<!--                </div>-->
<!--                &lt;!&ndash; 文章正文 &ndash;&gt;-->
<!--                <div class="form-group">-->
<!--                    <label for="content">文章正文</label>-->
<!--                    &lt;!&ndash; 文本区域 &ndash;&gt;-->
<!--                    <textarea class="form-control" id="content" name="content" rows="12"></textarea>-->
<!--                </div>-->
<!--                多个标签使用用英文逗号进行分分隔-->
                {{ note_post_form.media }}
                <!-- Django后台自带的模板as_p 表示表单中每个需输入元素将被p标签包裹-->
                {{ note_post_form.as_p }}

                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>

</main>


{% endblock %}

templates/blog/note_detail.html
{% extends 'base.html' %}

{% block title %}
主页
{% endblock %}

{% block content %}
<!-- Page Content-->
<section class="py-5" >
    <div class="container px-5 my-5" >
        <div class="row gx-5" >
            <div class="col-lg-3">
                <a href="{% url 'blog:note_index' %}?user={{ article.user.id }}">
                <div class="d-flex align-items-center mt-lg-5 mb-4">
<!--                    <img class="img-fluid rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />-->
                    <img class="img-fluid rounded-circle" src="/media/{{ article.user.tx }}" width="50" height="50" alt="..." />
                    <div class="ms-3">
                        <div class="fw-bold">{{ article.user.username }}</div>
                        <div class="text-muted">{{ article.user.profile }}</div>
                    </div>
                </div>
                </a>
            </div>
            <div class="col-lg-9">
                <!-- note content-->
                <article>
                    <!-- note header-->
                    <header class="mb-4">
                        <!-- note title-->
                        <h1 class="fw-bolder mb-1">{{ article.title }}</h1>
                        <!-- note meta content(更改时间)-->
                        <div class="text-muted fst-italic mb-2">{{ article.update_time }}
                            访问量：{{ article.click_num }}
<!--                            点赞:{{ article.love_num }}
 -->
<!--                            <a href="#" onclick="confirm_delete()">删除文章</a>-->
                            <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                            <a href="{% url 'blog:update_note' article.id %}">编辑文章</a>

                            <!-- 新增一个隐藏的表单,用来post提交，保证安全删除,防止csrf攻击 -->
                        <form
                              style="display:none;"
                              id="safe_delete"
                              action="{% url 'blog:delete_note' article.id %}"
                              method="POST"
                              >
                            {% csrf_token %}
                            <button type="submit">发送</button>
                        </form>
                        </div>
                        <!-- Post tags-->
                        {% if article.tags.all %}
                            {% for tag in article.tags.all %}
                        <a class="badge bg-secondary text-decoration-none link-light" href="{% url 'blog:note_index' %}?tag={{ tag }}">{{tag}}</a>
                            {% endfor %}
                        {% else %}
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">无标签</a>
                        {% endif %}
                    </header>

                    <!-- Preview image figure-->
<!--                                <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>-->
                    <figure class="mb-4"><img class="img-fluid rounded" src="/media/{{article.note_img}}" alt={{article.note_img}} /></figure>
                    <!-- Post content-->
                    <div id="content" class="mb-5">
                        <!--                        在 article.content 后加上 |safe 过滤器，来解决django会将输出的HTML代码进行转义的问题-->
                    <textarea>{{article.content}}</textarea>
                    </div>

                </article>


<!-- Comments section-->

                <!--// 提交评论区域的div-->
{% if request.session.userinfo %}
<div class="form-group  mb-4">
    {% csrf_token %}
        <div id="commentform_title">发表评论</div>
        <textarea class="form-control" rows="10" cols="60" id="comment_content"></textarea>
        <p><button  type="submit" onclick="sendcom()">提交评论</button></p>
</div>
{% else %}
<h5 class="row justify-content-center">
    <a href="{% url 'users:login' %}">请登录后回复</a>
</h5>
<br>
{% endif %}


                <!--    //评论展示区域的div -->
                <div class="comment_show">
                    <div class="feedback_area_title">评论列表</div>
                    <div class="comment_list">
                        {% if comment_list %}
                        <!--            // 循环展示评论的数据-->
                        <h4 class="comment_n">共有{{ comment_list.count }}条评论</h4>
                        {% for comment in comment_list %}
                        <!--                <div>-->
                        <p>第{{ forloop.counter}}楼 -> By:{{ comment.comment_author.username }} -> {{ comment.comment_time }} ->
                            <button class="reply" onclick="reply()" username={{ comment.comment_author.username }} pk={{ comment.pk }}>回复</button>
                        </p>
                        {# 在此处定义一个回复按钮，用户实现子评论,并且自定义属性username和pk，用于下面回复功能的实现 #}
                        {% if comment.pre_comment_id %} {#判断评论是否有父级评论#}
                        <p id="p">原评论内容：{{ comment.pre_comment.comment_content }}</p> {# 如果有父级评论，则在中间显示父级评论的评论内容#}
                        {% endif %}
                        <p>{{ comment.comment_content }}</p> {# 评论内容 #}
                        <hr>
                        <!--                </div>-->
                        {% endfor %}

                    </div>
                </div>
                {% else %}
                <h4 class="comment_n">共有0条评论</h4>
                {% endif %}
            </div>
        </div>
    </div>
</section>





<!--结束显示-->

<script>
    // 删除文章的函数
    //function confirm_delete() {
        // 调用layer弹窗组件
        //layer.open({
            // 弹窗标题
            //title: "确认删除",
            // 正文
            //content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            //yes: function(index, layero) {
                // 指定应当前往的 url
                //location.href='{% url "blog:delete_note" article.id %}'
            //},
        //})
    //}

    //安全删除
    function confirm_safe_delete() {
    layer.open({
        title: "确认删除",
        content: "确认删除这篇文章吗？",
        yes: function(index, layero) {
            $('form#safe_delete button').click();
            layer.close(index);
        }
    })
}



//{# 提交评论的JS，发送Ajax请求 #}


//{# 提交评论按钮的点击事件 #}
var pid = ""        //设置一个变量pid默认为空，用于后面作为数据库存储的父级评论的ID，如果没有父级评论则为空，子评论有父级评论
function sendcom(){
    $.ajax({
        url: '/comment/comment_control/',
        type: 'post',
        data: {// 提交的数据内容data
            comment_content: $("#comment_content").val(),
            csrfmiddlewaretoken:'{{ csrf_token }}',
            article_id: {{ article.id }},
            pid: pid
        },
        success: function (res){            // 本例中返回的数据仅仅用于在控制台打印而已
            //console.log(res)                //控制台打印返回的数据
            $("#comment_content").val("")   //提交完成后，清空评论输入框的内容
            //alert(window.JSON.stringify(res))
            //$(".comment_list").val(res)   //修改值
            //$(".comment_list").html(res)   //刷新值
            //location.href='{% url "blog:note_detail" article.id %}'<div>
                        var list = ''
            list=$('.comment_list').html()  //获取原来所有评论

            list+='<p>第'+res.comment_count+'楼 -> By:'+res.comment_author_name+ '-> '+ res.comment_time +'->'
            list+='<button class="reply" onclick="reply()" username=' + res.comment_author_name +' pk= '+res.pk+'>回复</button></p>'
            res.pre_comment_id
            if(res.pre_comment_id!=""){
                list+='<p id="p">原评论内容：'+res.pre_comment_comment+'</p>'
            }
            list+='<p>'+res.comment_content+'</p><hr>'

            $('.comment_list').html(list)
            $(".comment_n").html('共有'+res.comment_count+'条评论') //修改评论个数  注意这上下两个修改div放一块，因为测试发现分开放会导致这句不生效
            pid = ""                        //子评论提交完成后，将pid默认设置为空，恢复为默认的父评论
        }

    })
}

{# 回复按钮的点击事件 #}
function reply(){
    $("#comment_content").focus()       //回复按钮的事件，点击时，将光标聚集到评论输入框中
    var val = "@" + $('.reply').attr("username") + "\n"    //$(this)指代".reply"标签本身，获取这个标签的username值
    $("#comment_content").val(val)      // 回复时，自动在输入框加入：@要回复的人
    pid = $('.reply').attr("pk")            //当点击回复时，父评论ID不再为空，此时修改为：对应评论的主键值ID
}

</script>

{% endblock %}

templates/blog/update_note.html
{% extends 'base.html' %}

{% block title %}
更新博客
{% endblock %}
{% block content %}
<main class="bg">

<div class="container">
    <div class="row">
        <div class="col-12">
            <!-- 提交文章的表单 -->
<!--            <form  id ="update_note" method="post" action="" onsubmit="update_note()">-->
            <form  id ="update_note" method="post" action="">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                {{ note_post_form.media }}
                <!-- Django后台自带的模板as_p 表示表单中每个需输入元素将被p标签包裹-->
                {{ note_post_form.as_p }}
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
</main>

<!--<script>-->
<!--//手动指定formurl,绑定onsubmit再使用-->
<!--var curRoute = window.location.href //获取当前页面路由-->

<!--    function update_note()-->
<!--    {-->
<!--        document.update_note.action=curRoute-->
<!--    }-->
<!--</script>-->




{% endblock %}