blog/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time : 2022/7/3 13:07
# @Author : firworkseasycold
# @Email : 1476094297@qq.com
# @File : urls.py
# @Software: PyCharm
from django.urls import path
from . import views

# app_name="blog" #参看主路由分发是否需要

urlpatterns=[
    path('note_index',views.note_index,name='note_index'), #显示所有博客，可以根据？指定
    path('detail/<int:id>',views.note_detail,name='note_detail'),
    path('add',views.add_note,name='add_note'),
    path('delete/<int:id>',views.delete_note,name='delete_note'),
    path('update/<int:id>',views.update_note,name='update_note'),
    # path('searchtag/<int:id>',views.searchtag,name='search_tag'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,re_path,include #include为新添加内容,进行路由分发
from . import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [


    path('admin/', admin.site.urls),
    path('',views.index,name='index'),  #首页
    #表示之匹配 index 开头，并且index结尾的路径，等同上一个，使用re_path写法
    # re_path(r'^index/$', views.index, name='index'),#只有re_path可使用正则
    path('tt',views.tt,name='tt'),
    path('hello/<int:age>/<name>/', views.hello, {'key': "val"}), #路由参数传递示例，将int,age,key直接给后端
    #这里使用路由分发
    # 如果使用命名空间有问题:原因在app下的url.py要加app_name='';或者必须将include第⼀个参数设置为元组类型
    # 路由分发作用当一个项目中包含多个app，每个app中都有命名相同的标识符时，例如index，能够使每次访问都能得到想要的结果（访问指定变量）
    # path('firstapp/',include('firstapp.urls',namespace='firstapp')),
    path('firstapp/',include(('firstapp.urls','firstapp'),namespace='firstapp')), #这里使用元组来应对命名空间,测试用
    path('camera/',include('camera.urls',namespace='camera')), #测试用

    path('users/',include('users.urls',namespace='users')),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    re_path('mdeditor/', include('mdeditor.urls')),
    path('comment/',include(('comment.urls','comment'),namespace='comment')),
    path('democelery/',include(('democelery.urls','democelery'),namespace='democelery')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #这是配置上传的文件路径

users/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time : 2022/4/17 17:43
# @Author : firworkseasycold
# @Email : 1476094297@qq.com
# @File : urls.py
# @Software: PyCharm
from django.urls import path

from . import views

app_name='users' #使用二级路由必须项

urlpatterns=[
    path('register/',views.Register.as_view(),name='reg'),#注册，增加用户 cbv开发模式
    path("login/", views.Login.as_view(),name='login'),  #登录，cbv开发模式
    path("usersinfo/",views.Usersinfo.as_view(),name='usersinfo'),  #用户个人信息查看和修改

    path('logout/',views.logout,name='islogout'), #登出
    path('delete/<int:id>',views.delete_user,name='delete_user') ,#注销用户
    path('pwd_reset',views.Reset_passwords.as_view(),name='pwd_reset'), #邮件重置密码
    path('contact',views.Contactgly.as_view(),name='contact'), #留言
    path('introduce',views.introduce,name='introduce'), #问题介绍


    # path('register/',views.register,name='reg'),#注册，增加用户
    # path('reg/',views.reg), #注册的第二个写法测试用
    # path('login/',views.login,name='login'), #登录 #fbv开发模式


    # path('usersinfo/',views.usersinfo,name='usersinfo'),
    # path('list/',views.list,name='userslist'), #所有用户列表
    # path('delete/',views.delete_user,name='delete_user'), #删除用户
    path('test_form/',views.test_form), #测试form组件
]

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个元标记*必须*首先出现在头部；任何其他标题内容必须在*这些标记之后-->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="canonical" href="你的网页权威链接">
    <title>{% block title %}基础页面{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

<!--    bootstrap css-->
    <link href="{% static 'plugins/bootstrap-5.1.3/css/bootstrap.min.css' %}">

    <!-- markdwon解析css样式 -->
    <link href="{% static 'css/editormd.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/editormd.preview.css' %}" rel="stylesheet">


<!--    自定义-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    {% block css %}

    {% endblock %}

</head>
<body class="d-flex flex-column h-100">
<!-- 导航栏-->
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
            <a class="navbar-brand" href="{% url 'index' %}">Berryha-BLOG</a>
<!--            下拉按钮-->
            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">
                </span>
            </button>
            <div class="navbar-collapse collapse show" id="navbarSupportedContent" style="">
                <!-- 新增，搜索栏 -->
                <form role="search" action="{% url 'blog:note_index' %}">
          <input class="form-control" type="search" placeholder="搜索" aria-label="Search" name="search" required>
        </form>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">主页</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:note_index' %}">所有博客</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:contact' %}">联系我们</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:introduce' %}">常见问题</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">我的博客</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                            {% if request.session.userinfo %}
                                <li><a class="dropdown-item" href="{% url 'blog:note_index' %}?user={{ request.session.userinfo.uid }}">我的博客</a></li>
                            {% else %}
                            <li><a class="dropdown-item" href="{% url 'users:login' %}">我的创作</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'blog:add_note' %}">进入创作</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="#" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {% if request.session.userinfo %}
                                {{ request.session.userinfo.username }}
                                {% else %}
                                游客
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                            <li><a class="dropdown-item active" href="{% url 'users:login' %}">登录/注册</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:usersinfo' %}">个人信息</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:islogout' %}">登出</a></li>

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!--内容-->
{% block content %}
<!--<main class="flex-shrink-0">-->

<!--&lt;!&ndash;被继承的页面内容，改写&ndash;&gt;-->

<!--</main>-->
{% endblock %}

<!--页脚-->
<footer class="bg-dark py-4 mt-auto">
    <div class="container px-5">
        <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto">
                <div class="small m-0 text-white">
                    Copyright &copy; <a href=”http://beian.miit.gov.cn/” target=”_blank”>2022-树莓博客网</a>
                    <a href=”http://beian.miit.gov.cn/” target=”_blank”>苏ICP备2022037587号</a>
                </div>
            </div>
            <div class="col-auto">
                <a class="link-light small" href="https://www.dusaiphoto.com/article/2/">博客学习</a>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="https://www.runoob.com/try/bootstrap/">页面工具</a>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="{% url 'users:contact' %}">联系我们</a>
            </div>
        </div>
    </div>
</footer>

<!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里先引入 -->
<script src="{% static 'plugins/jq/jquery-3.6.0.min.js' %}"></script>
<!--<script src="{% static 'plugins/popper/popper-1.14.4.js' %}"></script>-->
<!-- Bootstrap core JS-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>-->
<script src="{% static 'plugins/bootstrap-5.1.3/js/bootstrap.min.js' %}"></script>
<!--<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>-->
<!-- 引入layer.js -->
<script src="{% static 'plugins/layer/layer.js' %}"></script>



<!-- Core 自定义的 JS-->
<script src="{% static 'js/scripts.js' %}"></script>

<!--django-mdeditor文章格式化-->
<!--参考https://pythonbrief.blog.csdn.net/article/details/121391577?spm=1001.2014.3001.5506-->
<script src="{% static 'js/editormd.min.js' %}"></script>
<script src="{% static 'js/marked.min.js' %}"></script>
<script src="{% static 'js/prettify.min.js' %}"></script>
<!--下面这句导致标题栏下拉和收缩失效,故-->
<!--<script src="{% static 'js/raphael.min.js' %}"></script>-->
<script src="{% static 'js/underscore.min.js' %}"></script>
<script src="{% static 'js/sequence-diagram.min.js' %}"></script>
<script src="{% static 'js/flowchart.min.js' %}"></script>
<script src="{% static 'js/jquery.flowchart.min.js' %}"></script>


<!--    评论使用ckeditor-->
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>


<script>
   $(function () {
    // js 解析markdown
    editormd.markdownToHTML("content", {
        //htmlDecode      : "style,script,iframe",  // you can filter tags decode
        emoji           : true,
        taskList        : true,
        tex             : true,  // 默认不解析
        flowChart       : true,  // 默认不解析
        sequenceDiagram : true,  // 默认不解析
    });

    $(".reference-link").each(function (i,obj) {
      console.log(obj)
    })
})
</script>



<!--#用django自带message给前端传递弹窗-->
{% if messages %}
<script>
{% for msg in messages %}
    alert('{{ msg.message }}');
{% endfor %}
</script>
{% endif %}
</body>
</html>