blog/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time : 2022/7/3 13:07
# @Author : firworkseasycold
# @Email : 1476094297@qq.com
# @File : urls.py
# @Software: PyCharm
from django.urls import path
from . import views

# app_name="blog" #参看主路由分发是否需要

urlpatterns=[
    path('note_index',views.note_index,name='note_index'), #显示所有博客，可以根据？指定
    path('detail/<int:id>',views.note_detail,name='note_detail'),
    path('add',views.add_note,name='add_note'),
    path('delete/<int:id>',views.delete_note,name='delete_note'),
    path('update/<int:id>',views.update_note,name='update_note'),
    # path('searchtag/<int:id>',views.searchtag,name='search_tag'),
]

camera/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time : 2022/4/23 23:34
# @Author : firworkseasycold
# @Email : 1476094297@qq.com
# @File : urls.py
# @Software: PyCharm
from django.urls import path

from . import  views

app_name='camerea' #使用二级路由必须项,或者不写此处改为路由分发时使用元组

urlpatterns=[
    path('index/',views.index,name='isloghome'), #这是登录后的主页
    path('show_all_img',views.show_all_img), #查看所有图片数据
    path('show_a_img',views.show_a_img), #查看一个图片数据
    path('upload_img',views.upload_img,name='upload_img'), #上传或者修改图片数据
    path('delete_img',views.delete_img), #删除图片数据
    path('camera',views.camera,name='face_rec'), #人脸识别
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,re_path,include #include为新添加内容,进行路由分发
from . import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [


    path('admin/', admin.site.urls),
    path('',views.index,name='index'),  #首页
    #表示之匹配 index 开头，并且index结尾的路径，等同上一个，使用re_path写法
    # re_path(r'^index/$', views.index, name='index'),#只有re_path可使用正则
    path('tt',views.tt,name='tt'),
    path('hello/<int:age>/<name>/', views.hello, {'key': "val"}), #路由参数传递示例，将int,age,key直接给后端
    #这里使用路由分发
    # 如果使用命名空间有问题:原因在app下的url.py要加app_name='';或者必须将include第⼀个参数设置为元组类型
    # 路由分发作用当一个项目中包含多个app，每个app中都有命名相同的标识符时，例如index，能够使每次访问都能得到想要的结果（访问指定变量）
    # path('firstapp/',include('firstapp.urls',namespace='firstapp')),
    path('firstapp/',include(('firstapp.urls','firstapp'),namespace='firstapp')), #这里使用元组来应对命名空间,测试用
    path('camera/',include('camera.urls',namespace='camera')), #测试用

    path('users/',include('users.urls',namespace='users')),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    re_path('mdeditor/', include('mdeditor.urls')),
    path('comment/',include(('comment.urls','comment'),namespace='comment')),
    path('democelery/',include(('democelery.urls','democelery'),namespace='democelery')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #这是配置上传的文件路径

users/urls.py
# !/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time : 2022/4/17 17:43
# @Author : firworkseasycold
# @Email : 1476094297@qq.com
# @File : urls.py
# @Software: PyCharm
from django.urls import path

from . import views

app_name='users' #使用二级路由必须项

urlpatterns=[
    path('register/',views.Register.as_view(),name='reg'),#注册，增加用户 cbv开发模式
    path("login/", views.Login.as_view(),name='login'),  #登录，cbv开发模式
    path("usersinfo/",views.Usersinfo.as_view(),name='usersinfo'),  #用户个人信息查看和修改

    path('logout/',views.logout,name='islogout'), #登出
    path('delete/<int:id>',views.delete_user,name='delete_user') ,#注销用户
    path('pwd_reset',views.Reset_passwords.as_view(),name='pwd_reset'), #邮件重置密码
    path('contact',views.Contactgly.as_view(),name='contact'), #留言
    path('introduce',views.introduce,name='introduce'), #问题介绍


    # path('register/',views.register,name='reg'),#注册，增加用户
    # path('reg/',views.reg), #注册的第二个写法测试用
    # path('login/',views.login,name='login'), #登录 #fbv开发模式


    # path('usersinfo/',views.usersinfo,name='usersinfo'),
    # path('list/',views.list,name='userslist'), #所有用户列表
    # path('delete/',views.delete_user,name='delete_user'), #删除用户
    path('test_form/',views.test_form), #测试form组件
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Usersdata(models.Model):
    """用户表"""
    #使用二元分组
    user_sex=(
        ('m','男'),
        ('w','女')
    )
    #第一个元素是要存入database的数据，第二个元素是admin的界面显示的数据。
    username = models.CharField(max_length=128, verbose_name='用户名',unique=True) #唯一
    password = models.CharField(max_length=256, verbose_name='密码')
    sex = models.CharField(max_length=1, choices=user_sex, verbose_name='性别', default='m')
    email = models.EmailField(verbose_name='邮箱', unique=True) #唯一
    ip = models.CharField(max_length=128, verbose_name='IP地址')
    profile = models.CharField(max_length=50, verbose_name=' 简介', default='该用户没有简介')
    tx=models.ImageField(upload_to='uploads/tx/%Y/%m/%d',verbose_name='用户头像',default='uploads/tx/tx.jpeg')
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    update_time = models.DateTimeField('更新时间', auto_now=True)


    objects = models.Manager()  #防止views里使用models.Usersdata.objects进行orm操作不提示并且报淡黄色

    #使用__str__魔法函数帮助djangoshell中人性化显示对象信息；
    # 使用方法python manage.py shell可以进行查看;
    # 或者登录djanngo后台表里查看每条数据的显示样式
    def __str__(self):
        return "用户:%s"%(self.username) #使用__str__方法修改print（此类的实例化对象）的默认输出



    class Meta: #忘记怎么用记得去查这个类的所有属性
        ordering=['username'] #按照人名升序排序
        # ordering=['-username'] #按照人名降序排序
        # ordering=['？username'] #按照人名随机排序
        db_table='users' #设置表名，比如改为uu，admin里表就叫uu
        #verbose_name指定在admin管理界面中显示中文；
        # verbose_name表示单数形式的显示，
        # verbose_name_plural表示复数形式的显示；
        # 中文的单数和复数一般不作区别。
        verbose_name='用户' #指定模型类名字
        verbose_name_plural=verbose_name #指定模型类名字（复数）

# class Usersdata(AbstractUser):
#     user_sex = (
#                 ('m','男'),
#                 ('w','女')
#             )
#     sex = models.CharField(max_length=1, choices=user_sex, verbose_name='性别', default='m')

users/views.py
import hashlib
import os
import random
import re
import string

from django import forms
from django.db.models import Q
from django.forms import Form, fields, ModelForm
from django.http import HttpResponseRedirect  # HttpResponseRedirect仅可以接收url作为参数传入。
from django.shortcuts import render, HttpResponse, redirect  # redirect可以接收model、view或者url作为参数传入，并返回HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.core import mail

from mysite import settings
from mysite.settings import EMAIL_HOST_USER
from . import models
# from .models import Usersdata #或者写成这样
from tools.my_tool import *  # 这里红色不是错误（标记源根即可解决），tools为项目下与各app包同级别的自建包
from .tasks import send_pwd_email
from blog.models import Note
from camera.models import Face_img


# Create your views here.
class Login(View):
    def get(self, request):
        if request.session.get('userinfo', False):
            return HttpResponseRedirect(reverse('index'))  # 302跳转，使用reverse别名写法
        # 检查Cookies
        userinfo = request.COOKIES.get('userinfo')
        # print(userinfo)
        if userinfo:
            # 回写session
            request.session['userinfo'] = userinfo
            return HttpResponseRedirect(reverse('index'))  # 302跳转，使用reverse别名写法
            # return HttpResponse('已登录2')
        return render(request, 'users/login.html')  # 登陆失败重新渲染登录页面

    def post(self, request):
        useroremail = request.POST['useroremail']
        password = request.POST['password']
        pattern = r'^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$'
        # 使用re库的match方法校验传入的邮箱参数是否合理,是否与表达式匹配
        if re.match(pattern, useroremail) is not None:
            # 是邮箱
            try:
                user = models.Usersdata.objects.get(email=useroremail)
            except Exception as e:
                # print(e)
                # 使用django messages
                messages.error(request, "对不起，您的邮箱地址有误")
                return render(request, 'users/login.html')
        else:
            # 是用户名
            try:
                user = models.Usersdata.objects.get(username=useroremail)
            except Exception as e:
                messages.error(request, "对不起，您的用户名有误")
                return render(request, 'users/login.html')
        # 比对密码
        m = hashlib.md5()
        m.update(password.encode())
        if m.hexdigest() != user.password:
            messages.error(request, "对不起，密码验证失败，请重新输入")
            return render(request, 'users/login.html')
        # session记录会话状态
        request.session['userinfo'] = {"username": user.username, "uid": user.id}
        # print({"uid": user.id})
        # resp = HttpResponseRedirect('/index')
        resp=HttpResponseRedirect(reverse('index'))
        # 如果打勾-则于客户端存cookie【username,uid】,时间3天,cookie是长期数据
        if 'remember' in request.POST:  # 具体看开发者工具网络-载荷里的表单数据有没有remember
            resp.set_cookie('userinfo', {"username": user.username, "uid": user.id}, 3600 * 24 * 3)
        # messages.success(request, "欢迎您")
        return resp


class Register(View):
    """
    注册
    """

    def get(self, request):
        # print('正在访问')
        return render(request, 'users/register.html')

    def post(self, request):
        # print('正在注册')
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        # 1两个密码要保持一致
        if password1 != password2:
            messages.error(request, '两次输入的密码不一致，请重新输入')
            return render(request, 'users/register.html')

        # 优化：密码加盐-哈希算法，给明文，计算出定长的值，一般用md5;应用于密码处理和文件完整性校验
        m = hashlib.md5()
        m.update(password1.encode())  # 传参数必须是字节串，而不能是字符串，所以需要encode
        password_m = m.hexdigest()  # 十六进制数据字符串值
        # password_m=m.digest()#返回二进制数据字符串值
        # 2.邮箱格式是否正确（如果可以建议由前端判断）
        pattern = r'^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$'
        # 使用re库的match方法校验传入的邮箱参数是否合理,是否与表达式匹配
        if re.match(pattern, email) is None:
            # 不是邮箱
            messages.error(request, "对不起，您的邮箱格式有误,请重新输入")
            return render(request, 'users/register.html')

        # 3.当前用户名是否可用 需要orm操作查询
        old_users = models.Usersdata.objects.filter(username=username)
        old_email = models.Usersdata.objects.filter(email=email)
        if old_users:
            messages.error(request, '用户名已注册')
            return render(request, 'users/register.html')
        if old_email:
            messages.error(request, '邮箱已被使用')
            return render(request, 'users/register.html')
        # 4.插入数据【明文处理密码-实际应用需要加密】
        # models.Usersdata.objects.create(username=username,password=password1,email=email)
        # models.Usersdata.objects.create(username=username, password=password_m, email=email)  # 优化：密码使用哈希值
        # 优化 插入问题 解决并发1062报错-使用try
        try:
            user = models.Usersdata.objects.create(username=username, password=password_m, email=email)  # 优化：密码使用哈希值
        except Exception as e:
            # 有可能报错，重复插入（唯一索引并发写入问题）：需要使用redis消息队列进行优化
            # print('--create user error %s' % (e))  # 开发时打印后台查看报错
            # return HttpResponse('注册失败')
            messages.error(request, '系统繁忙，请重新尝试')
            return render(request, 'users/register.html')

        # 优化：注册免登录一天 存入session,服务端，保持会话登录状态一天
        # request.session['username']=username #存入session
        # request.session['uid']=user.id #因为主键查询比唯一索引快，所以可以session可以多存个id来用于查询
        request.session['userinfo'] = {"username": username, "uid": user.id}
        # print(user.id)
        # 修改session存储时间，默认14天 在settings设SESSION_COOKIE_AGE = 86400

        url = reverse('index')
        # print(url) #/index/
        resp = HttpResponseRedirect(url)
        if 'remember' in request.POST:  # 具体看开发者工具网络-载荷里的表单数据有没有remember
            resp.set_cookie('userinfo', {"username": user.username, "uid": user.id}, 3600 * 24 * 3)
        messages.success(request, '登录成功')
        return resp  # 302跳转，使用reverse别名写法

@check_login
def logout(request):
    """
    退出登录
    :param request:
    :return:
    """
    # 删除session
    if 'userinfo' in request.session:
        del request.session['userinfo']
        request.session.flush()  # 删除一条记录包括(session_key session_data expire_date)三个字段
    # 删除cookies
    resp = HttpResponseRedirect('/users/login')  # 302跳转到登录页面
    if 'userinfo' in request.COOKIES:
        resp.delete_cookie('userinfo')
    return resp


@check_login
def delete_user(request,id):
    """注销用户,这里使用get,如果防止csrf攻击,请用post"""
    user = models.Usersdata.objects.get(id=id)  # 获取要删除的对象(id从usersinfo拿到)
    # 从session获取获取当前登录的用户
    uid = request.session.get('userinfo', False).get('uid', False)  # 获取当前登录的用户id
    user_ses = models.Usersdata.objects.get(id=uid)  # 获取当前登录用户对象，这个写法接着delete，可能会报错
    # 判断登录用户和待删除是否一个人
    if user_ses==user:

        logout(request)
        user.delete()
        messages.success(request, "用户已成功注销")
        return HttpResponseRedirect('users:login')
    else:
        return HttpResponse('你没有权限注销用户')


# @check_login
# def usersinfo(request):
#     '''
#     	查看更新修改用户信息
#     	通过POST方法提交表单，修改用户信息
#     	GET方法进入用户信息页面
#     '''
#     # 获取用户对象数据
#     uid = request.session.get('userinfo', False).get('uid', False) #获取当前登录的用户id
#     user = models.Usersdata.objects.get(id=uid)  # 获取当前用户所有信息
#     face_img = Face_img.objects.get(user_id=uid) #获取身份验证图片
#     # 判断用户是否为POST提交表单数据
#     if request.method == "POST":
#         # 获取表单数据
#         username = request.POST['username']  #如果为空会报错MultiValueDictKeyError
#         username = request.POST.get('username','这是我设置的默认值')  #两者等价如果为空不会报错
#         sex = request.POST['sex']
#         email = request.POST['email']
#         password = request.POST['password']
#         # 当前修改的用户名和邮箱是否可用 需要orm操作查询
#         old_users = models.Usersdata.objects.filter(username=username)
#         old_email = models.Usersdata.objects.filter(email=email)
#         if old_users:
#             return HttpResponse('用户名已注册')
#         if old_email:
#             return HttpResponse('邮箱已使用')
#         # 优化：密码加盐-哈希算法，给明文，计算出定长的值，一般用md5;应用于密码处理和文件完整性校验
#         m = hashlib.md5()
#         m.update(password.encode())  # 传参数必须是字节串，而不能是字符串，所以需要encode
#         password_m = m.hexdigest()  # 十六进制数据字符串值
#         # password_m=m.digest()#二进制数据字符串值
#
#         try:
#             #执行保存
#             user.username=username
#             user.sex=sex
#             user.password=password_m
#             user.username=username
#             user.save()
#             # 完成后返回到usersinfo页面
#             # return redirect("user:usersinfo")
#             return HttpResponse('用户信息更新成功')
#         except Exception as e:
#             # 如果数据不合法，返回错误信息
#             return HttpResponse("修改个人信息失败，请重新尝试！或联系管理员")
#     # 如果用户GET请求获取数据
#     else:
#         content = {"user": user, "fontend_face_img":face_img}
#         return render(request, 'users/usersinfo.html', context=content)


# 要在CBV视图中使用我们上面的check_login装饰器，有以下三种方式：
#
# 都要先导入这个方法： from django.utils.decorators import method_decorator
#
# 1. 加在CBV视图的get或post方法上
#
# 2. 加在dispatch方法上
#
# 3. 直接加在视图类上，但method_decorator必须传 name 关键字参数（如果get方法和post方法都需要登录校验的话就写两个装饰器。）

class Usersinfo(View):
    @method_decorator(check_login, name="get")
    # @check_login #在cbv模式下这么写装饰器不生效会有Usersinfo的object没有session报错
    def get(self, request):
        # 查看用户数据
        uid = request.session.get('userinfo', False).get('uid', False)  # 获取当前登录的用户id
        usersdata = models.Usersdata.objects.get(id=uid)  # 获取当前用户所有信息
        content = {"usersdata": usersdata}
        return render(request, 'users/usersinfo.html', context=content)

    @method_decorator(check_login, name="post")
    def post(self, request):
        # 修改用户数据(不包括头像，我设置的跳转至图片上传）
        uid = request.session.get('userinfo', False).get('uid', False)  # 获取当前登录的用户id
        usersdata = models.Usersdata.objects.get(id=uid)  # 获取当前用户所有信息

templates/users/contact.html
{% extends 'base.html' %}

{% block title %}
联系我们
{% endblock %}



{% block content %}
        <main class="flex-shrink-0">
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Contact form-->
                    <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
                        <div class="text-center mb-5">
                            <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                            <h1 class="fw-bolder">Get in touch</h1>
                            <p class="lead fw-normal text-muted mb-0">We'd love to hear from you</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
                            <div class="col-lg-8 col-xl-6">
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- * * SB Forms Contact Form * *-->
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- This form is pre-integrated with SB Forms.-->
                                <!-- To make this form functional, sign up at-->
                                <!-- https://startbootstrap.com/solution/contact-forms-->
                                <!-- to get an API token!-->
                                <form id="contactForm" action="{% url 'users:contact' %}" method="POST">
                                    {% csrf_token %}
                                    <!-- Name input-->
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" name="username" />
                                        <label for="name">Full name</label>
                                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                    </div>
                                    <!-- Email address input-->
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" name="email" />
                                        <label for="email">Email address</label>
                                        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                                    </div>

                                    <div class="form-floating mb-3">
                                        <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required" name="message"></textarea>
                                        <label for="message">Message</label>
                                        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                                    </div>

                                    <!-- Submit Button-->
                                    <div class="d-grid"><button class="btn btn-primary btn-lg" id="submitButton" type="submit">Submit</button></div>
                                </form>
                            </div>
                        </div>
                    </div>

                </div>
            </section>
        </main>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block title %}
登录页面
{% endblock %}

{% block css %}
<style>

.bg{
    background:url({%static '/img/login.gif' %}) no-repeat center;
    height: 100%;
    display: flex;
    align-items: center;
    padding-top: 40px;
    padding-bottom: 40px;
    background-size:cover;
    font-size: 15px;
}

  .form-signin{
    font-weight: var(--bs-body-font-weight);
    line-height: var(--bs-body-line-height);
    color: var(--bs-body-color);
    -webkit-text-size-adjust: 100%;
    -webkit-tap-highlight-color: transparent;
    text-align: center!important;
    box-sizing: border-box;
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
    }
</style>
{% endblock %}

{% block content %}
<main class="bg">
  <div class="form-signin">
    <form action="{% url 'users:login' %}" method="POST">
      {% csrf_token %}
    <img class="img-fluid rounded-circle" src="{% static 'img/login_1.gif' %}" alt="" width="100" height="100">
    <h1 class="h3 mb-3 fw-normal">欢迎登录</h1>
    <div class="form-floating">
      <input type="text" class="form-control" id="floatingInput" placeholder="name or name@example.com" name="useroremail">
      <label for="floatingInput">邮件/用户名</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
      <label for="floatingPassword">密码</label>
    </div>

    <div class="checkbox mb-3">
      <label style="float:left">
        <input type="checkbox" value="remember"> 记住用户
      </label>
      <label style="float:right">
        <a href="{% url 'users:pwd_reset' %}">忘记密码</a>
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">登录</button>
        <a href="{% url 'users:reg' %}">没有账号？立即注册</a>
  </form>
  </div>
</main>
{% endblock %}

templates/users/reset_passwords.html
{% extends 'base.html' %}

{% block title %}
重置密码
{% endblock %}

{% block content %}


<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="jumbotron">
				<br>
				<h2>
					还没注册?点击<a href="{% url 'users:reg' %}">此处</a>进行注册
				</h2>
				<p>
					这里是密码重置页面，输入账号或者邮箱，将发送一个系统生成的随机密码给您的邮箱,用于您的此次登录
				</p>
				<p>
					您可以在登陆后自行修改个人密码
				</p>


    <form method="post" action="{% url 'users:pwd_reset' %}">
    {%csrf_token%}
    <p>
        <input type="text" name="useroremail" placeholder="用户名或者邮箱">
    </p>
<!--    <p>-->
<!--        <input type="submit" value="确定重置">-->
<!--    </p>-->
    <button type="submit" class="btn btn-primary">发送邮件</button>
    </form>

			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/users/test_form.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>users_add</title>
</head>
<body>
<form method="post" action="#">
    {% csrf_token %}
    {{ form.name }}
    {{ form.age }}
    {{ form.salary }}
<input type="submit">
</form>
</body>
</html>

templates/users/usersinfo.html
{% extends 'base.html' %}

{% block title %}
用户信息
{% endblock %}

{% block css %}
<style>

.bg{
    background:url({% static '/img/usersinfo.jpg' %}) no-repeat center;
    height: 100%;
    display: flex;
    align-items: center;
    padding-top: 40px;
    padding-bottom: 40px;
    background-size:cover;
    font-size: 15px;
}

  .form-signin{
    font-weight: var(--bs-body-font-weight);
    line-height: var(--bs-body-line-height);
    color: var(--bs-body-color);
    -webkit-text-size-adjust: 100%;
    -webkit-tap-highlight-color: transparent;
    text-align: center!important;
    box-sizing: border-box;
    width: 100%;
    max-width: 400px;
    padding: 15px;
    margin: auto;
    }
</style>
{% endblock %}


{% block content %}
<main class="bg">

<div class="form-signin">
    <h1 class="h3 mb-3 fw-normal">用户信息</h1>
<form action="{% url 'users:usersinfo' %}" method="post" enctype="multipart/form-data">

{% csrf_token %}
<!--usersdata.tx-->
<img  class="img-fluid rounded-circle" src="/media/{{ usersdata.tx }}" alt="{{usersdata.tx}}" width='200' height='200' id="tx">
<input type="file" class="form-control" name="tx" id="floatingTx" accept="image/*" onchange="changepic(this)">
<div class="form-floating">
<input type="text" class="form-control" id="floatingInput" placeholder="6位以下中英文数字组合" value="{{usersdata.username}}" name="username">
<label for="floatingInput">用户名</label>
</div>
<div class="form-floating">
<input type="text" class="form-control" id="floatingSex" placeholder="男或女" value="{{usersdata.sex}}" name="sex">
<label for="floatingInput">性别</label>
</div>
<div class="form-floating">
<input type="text" class="form-control" id="floatingPassword" placeholder="Password" value="{{usersdata.password}}" name="password">
<label for="floatingPassword">密码</label>
</div>
<div class="form-floating">
<input type="text" class="form-control" id="floatingEmail" placeholder="Email"  value="{{usersdata.email}}" name="email">
<label for="floatingEmail">邮箱</label>
</div>
<div class="form-floating">
<input type="text" class="form-control" id="floatingProfile" placeholder="Profile"  value="{{usersdata.profile}}" name="profile">
<label for="floatingProfile">简介</label>
</div>




<button class="w-100 btn btn-lg btn-primary" type="submit">提交修改</button>
<div>

<a href="#" onclick="delete_user()">注销用户</a>
<a href="C">刷新显示</a>
<!--          <label>-->
<!--        <a href="{% url 'camera:upload_img' %}">修改头像</a>-->
<!--      </label>-->
</div>
</form>
</div>



</main>

<script>
//参考https://blog.csdn.net/weixin_38023551/article/details/78318532?spm=1001.2101.3001.6650.3&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-3-78318532-blog-117828046.pc_relevant_default&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-3-78318532-blog-117828046.pc_relevant_default&utm_relevant_index=4
    //展示上传的图片 ,存在
    //filereader 的方法
    function changepic() {
        var reads= new FileReader();
        f=document.getElementById('floatingTx').files[0];
        reads.readAsDataURL(f);
        reads.onload=function (e) {
            document.getElementById('tx').src=this.result;
        };
    }

    //注销用户
    function delete_user(){
    //调用layer弹窗组件
    layer.open({
        //弹窗标题:
        title:"确认删除",
        //正文
        content:"确认删除所有信息并注销吗",
        yes:function(index,layero){
        //前往指定url
        location.herf='{% url 'users:delete_user' usersdata.id %}'
        },
    })
    }

</script>
{% endblock %}